# Generated by Django 5.0.3 on 2024-03-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_narration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="narration",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
