# Generated by Django 5.0.4 on 2024-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_audio_narration_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio_file",
            field=models.FileField(null=True, upload_to="audio/"),
        ),
    ]
